# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e7573879dc82ecdf93f527ee19512d0"
application_url = "https://acids-donors-locale-named.trycloudflare.com"
embedded = true
name = "boa-home-task-DG"
handle = "boa-home-task-dg"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-119.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://acids-donors-locale-named.trycloudflare.com/auth/callback",
  "https://acids-donors-locale-named.trycloudflare.com/auth/shopify/callback",
  "https://acids-donors-locale-named.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
